### ISSUE TITLE
no matchi ng package found.

### ISSUE THREAD

**Issue by urfusion** [yarcode/yii2-swagger#1]
- Installation request for yarcode/yii2-swagger ^0.1.0 -> satisfiable by yar
code/yii2-swagger[0.1].
    - yarcode/yii2-swagger 0.1 requires bower-asset/swagger-ui ~2.1 -> no matchi
ng package found.

**Comment by metalagman** [comment]
Please install this plugin https://packagist.org/packages/fxp/composer-asset-plugin
